### ISSUE TITLE
[Error] SecurityConfig CORS errors

### ISSUE THREAD

**Issue by dlwltn0430** [Apptive2022-1/apptive-18th-team4#23]
## 문제
CORS 에러 발생

## 버그 맥락
회원가입 기능 테스트를 위해 프론트에서 http://3.34.82.40:8080/auth/signup로 요청을 보냈더니 다음과 같은 에러가 발생했다.

**Access to XMLHttpRequest at 'http://3.34.82.40:8080/auth/signup' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**
**POST http://3.34.82.40:8080/auth/signup net::ERR_FAILED**

## 올바른 동작
요청 보내는 것을 성공하면 response의 status 값이 200으로 떠야한다.

## 스크린샷
![image](https://user-images.githubusercontent.com/101401447/229065311-42706cf3-6d53-447d-96a3-2479c0706e1d.png)
![image](https://user-images.githubusercontent.com/101401447/229065959-cf60fc80-bd42-4c81-ae4b-5f14a023ecf8.png)

**Comment by ChoMinGi** [comment]
해당 에러 확인후 수정시도하였지만 해결되지 않음

추후 func 3까지 개발 완료후 디버깅 예정

**Comment by ChoMinGi** [comment]
@dlwltn0430 
스프링은....... 잘못이없었습니다....

단지..... aws 인바운드 규칙에...... react 를 실행하는 클라이언트의 주소(IP)가 필요했을뿐입니다.............

**Comment by ChoMinGi** [comment]
![image](https://user-images.githubusercontent.com/81455273/233925079-5f1e3aef-c787-4c0f-ae22-dca11aeee58b.png)
임의의 메인페이지 테스팅




![image](https://user-images.githubusercontent.com/81455273/233925646-06eb3cc8-6b89-4e88-9e8b-f7846b786e17.png)
![image](https://user-images.githubusercontent.com/81455273/233925778-96918a96-e701-40f4-8bed-5c450384a489.png)


200 OK~
