### ISSUE TITLE
빈 강의실 조회(위치순, 즐겨찾기순) API response body 수정 요청

### ISSUE THREAD

**Issue by dlwltn0430** [Apptive2022-1/apptive-18th-team4#62]
https://github.com/ApptiveDev/apptive-18th-team4-frontend/blob/jisu/src/components/tab/data.json

위와 비슷한 형식으로 수정 부탁드립니다!

**Comment by ChoMinGi** [comment]
```
availableNow": [
            {
                "roomNum": "9201",
                "endTime": "18:30"
            }
        "availableSoon": [
            {
                "roomNum": "9301",
                "startTime": "15:00",
                "endTime": "17:30"
            }
            
```

변수명이 같아서 착오가 생길수 있을것 같다고 생각듭니다.

availableNow의 endTime을 availableTime으로 변경 요청드립니다.

엄격하게 명명하자면 availableSoon도 lectureStartTime 과 같이 변경가능하나 다른 옵션이 존재하지 않기에 이 두가지는 그대로 사용해도 좋다고 생각합니다.

**Comment by dlwltn0430** [comment]
확인했습니다!

**Comment by ChoMinGi** [comment]
#63 반영하였습니다!
